name: Format Code

on:
  push:
    branches:
      - master # Adjust to your main branch name

jobs:
  format-code:
    runs-on: windows-latest # Change the runs-on value to windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Format code
        run: npx prettier --write "src/**/*.ts" "src/**/*.tsx"

      - name: Commit changes
        run: |
          git config user.name "rahul6169"
          git config user.email "rahulbalakrishnan6169@gmail.com"
          git add .
          git commit -m "Auto-format code" --no-verify

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
